import {
  Calendar,
  Users,
  ClipboardList,
  BarChart3,
  Settings,
  DollarSign,
  Package,
  MessageSquare,
  Clock,
  UtensilsCrossed,
} from 'lucide-react';
import { Feature } from '@/lib/types';

const features: Feature[] = [
  {
    title: 'Staff Scheduler',
    description:
      'Build weekly schedules based on employee availability and priority',
    icon: Calendar,
    href: '/scheduler',
    color: 'bg-blue-500',
    available: true,
    roles: ['admin', 'manager'],
  },
  {
    title: 'Employee Management',
    description: 'Manage employee profiles, contracts, and performance',
    icon: Users,
    href: '/employees',
    color: 'bg-green-500',
    available: true,
    roles: ['admin', 'manager'],
  },
  {
    title: 'Staff Schedule',
    description: 'Submit your weekly availability and view your schedule',
    icon: Clock,
    href: '/availability',
    color: 'bg-indigo-500',
    available: true,
    roles: ['employee'],
  },
  {
    title: 'Reservation Management',
    description: 'Manage table reservations and floor layouts',
    icon: UtensilsCrossed,
    href: '/reservations',
    color: 'bg-rose-500',
    available: true,
    roles: ['admin', 'manager'],
  },
  {
    title: 'Order Management',
    description: 'Track and manage customer orders in real-time',
    icon: ClipboardList,
    href: '/orders',
    color: 'bg-purple-500',
    available: false,
    roles: ['admin', 'manager'],
  },
  {
    title: 'Analytics & Reports',
    description: 'View insights on sales, staff performance, and operations',
    icon: BarChart3,
    href: '/analytics',
    color: 'bg-orange-500',
    available: false,
    roles: ['admin', 'manager'],
  },
  {
    title: 'Inventory Management',
    description: 'Track stock levels and manage suppliers',
    icon: Package,
    href: '/inventory',
    color: 'bg-teal-500',
    available: false,
    roles: ['admin', 'manager'],
  },
  {
    title: 'Financial Overview',
    description: 'Monitor revenue, expenses, and profit margins',
    icon: DollarSign,
    href: '/finance',
    color: 'bg-yellow-500',
    available: false,
    roles: ['admin', 'manager'],
  },
  {
    title: 'Customer Feedback',
    description: 'Collect and analyze customer reviews and ratings',
    icon: MessageSquare,
    href: '/feedback',
    color: 'bg-pink-500',
    available: false,
    roles: ['admin', 'manager'],
  },
  {
    title: 'Settings',
    description: 'Configure system preferences and restaurant details',
    icon: Settings,
    href: '/settings',
    color: 'bg-gray-500',
    available: true,
    roles: ['admin', 'manager', 'employee'],
  },
];

export default features;
